In [1]:
import polars as pl

In [2]:
prajith_path = "../export/error_messages_updated.csv"

In [3]:
df_error = pl.read_csv(prajith_path)
df_error

shape: (3_321, 9)
┌──────┬─────────────┬─────────────┬───────┬───┬─────────────┬─────────────┬─────────┬─────────────┐
│      ┆ ID          ┆ Session     ┆ Run   ┆ … ┆ Errors      ┆ Log         ┆ Lengths ┆ Failed      │
│ ---  ┆ ---         ┆ ---         ┆ ---   ┆   ┆ ---         ┆ ---         ┆ ---     ┆ Command     │
│ i64  ┆ str         ┆ str         ┆ str   ┆   ┆ str         ┆ str         ┆ i64     ┆ ---         │
│      ┆             ┆             ┆       ┆   ┆             ┆             ┆         ┆ str         │
╞══════╪═════════════╪═════════════╪═══════╪═══╪═════════════╪═════════════╪═════════╪═════════════╡
│ 0    ┆ NDARINVLBJ8 ┆ baselineYea ┆ 02LN  ┆ … ┆ /bin/cp /ho ┆             ┆ 654     ┆ /usr/local/ │
│      ┆ E0XH        ┆ r1Arm1      ┆       ┆   ┆ me/axon/rkm ┆ /bin/cp /ho ┆         ┆ fsl/bin/fea │
│      ┆             ┆             ┆       ┆   ┆ 160630/s…   ┆ me/axon/rkm ┆         ┆ t_model …   │
│      ┆             ┆             ┆       ┆   ┆             ┆ 160630/…    ┆         ┆             │
│ 1    ┆ NDARINVP4HD ┆ baselineYea ┆ 02LN+ ┆ … ┆ /bin/cp /ho ┆             ┆ 654     ┆ /usr/local/ │
│      ┆ 6R8B        ┆ r1Arm1      ┆       ┆   ┆ me/axon/rkm ┆ /bin/cp /ho ┆         ┆ fsl/bin/fea │
│      ┆             ┆             ┆       ┆   ┆ 160630/s…   ┆ me/axon/rkm ┆         ┆ t_model …   │
│      ┆             ┆             ┆       ┆   ┆             ┆ 160630/…    ┆         ┆             │
│ 2    ┆ NDARINVPF40 ┆ baselineYea ┆ 01LN  ┆ … ┆ /bin/cp /ho ┆             ┆ 654     ┆ /usr/local/ │
│      ┆ 52KB        ┆ r1Arm1      ┆       ┆   ┆ me/axon/rkm ┆ /bin/cp /ho ┆         ┆ fsl/bin/fea │
│      ┆             ┆             ┆       ┆   ┆ 160630/s…   ┆ me/axon/rkm ┆         ┆ t_model …   │
│      ┆             ┆             ┆       ┆   ┆             ┆ 160630/…    ┆         ┆             │
│ 3    ┆ NDARINV3CUD ┆ baselineYea ┆ 02LN+ ┆ … ┆ /bin/cp /ho ┆             ┆ 654     ┆ /usr/local/ │
│      ┆ M6MC        ┆ r1Arm1      ┆       ┆   ┆ me/axon/rkm ┆ /bin/cp /ho ┆         ┆ fsl/bin/fea │
│      ┆             ┆             ┆       ┆   ┆ 160630/s…   ┆ me/axon/rkm ┆         ┆ t_model …   │
│      ┆             ┆             ┆       ┆   ┆             ┆ 160630/…    ┆         ┆             │
│ 4    ┆ NDARINVC1VM ┆ baselineYea ┆ 02LN  ┆ … ┆ /bin/cp /ho ┆             ┆ 654     ┆ /usr/local/ │
│      ┆ 5JUL        ┆ r1Arm1      ┆       ┆   ┆ me/axon/rkm ┆ /bin/cp /ho ┆         ┆ fsl/bin/fea │
│      ┆             ┆             ┆       ┆   ┆ 160630/s…   ┆ me/axon/rkm ┆         ┆ t_model …   │
│      ┆             ┆             ┆       ┆   ┆             ┆ 160630/…    ┆         ┆             │
│ …    ┆ …           ┆ …           ┆ …     ┆ … ┆ …           ┆ …           ┆ …       ┆ …           │
│ 3316 ┆ NDARINV0CFR ┆ baselineYea ┆ 01LN+ ┆ … ┆ /bin/cp /ho ┆ <HTML><HEAD ┆ 1862    ┆ /usr/local/ │
│      ┆ 33F0        ┆ r1Arm1      ┆       ┆   ┆ me/axon/rkm ┆ >           ┆         ┆ fsl/bin/fsl │
│      ┆             ┆             ┆       ┆   ┆ 160630/s…   ┆ <!--refresh ┆         ┆ _sub -T …   │
│      ┆             ┆             ┆       ┆   ┆             ┆ start-…     ┆         ┆             │
│ 3317 ┆ NDARINV2NV4 ┆ baselineYea ┆ 02LN  ┆ … ┆ /bin/cp /ho ┆ <HTML><HEAD ┆ 1856    ┆ /usr/local/ │
│      ┆ C2CL        ┆ r1Arm1      ┆       ┆   ┆ me/axon/rkm ┆ >           ┆         ┆ fsl/bin/fsl │
│      ┆             ┆             ┆       ┆   ┆ 160630/s…   ┆ <!--refresh ┆         ┆ _sub -T …   │
│      ┆             ┆             ┆       ┆   ┆             ┆ start-…     ┆         ┆             │
│ 3318 ┆ NDARINV42N7 ┆ baselineYea ┆ 01LN  ┆ … ┆ /bin/cp /ho ┆ <HTML><HEAD ┆ 1856    ┆ /usr/local/ │
│      ┆ 0P8A        ┆ r1Arm1      ┆       ┆   ┆ me/axon/rkm ┆ >           ┆         ┆ fsl/bin/fsl │
│      ┆             ┆             ┆       ┆   ┆ 160630/s…   ┆ <!--refresh ┆         ┆ _sub -T …   │
│      ┆             ┆             ┆       ┆   ┆             ┆ start-…     ┆         ┆             │
│ 3319 ┆ NDARINV8FYG ┆ baselineYea ┆ 02LN  ┆ … ┆ /bin/cp /ho ┆ <HTML><HEAD ┆ 1856    ┆ /usr/local/ │
│      ┆ 1NE5        ┆ r1Arm1      ┆       ┆   ┆ me/axon/rkm ┆ >           ┆         ┆ fsl/bin/fsl │
│      ┆             ┆             ┆       ┆   ┆ 160630/s…   ┆ <!--refresh ┆         ┆ _sub -T …   │
│      ┆             ┆             ┆       ┆   ┆             ┆ start-…     ┆         ┆             │
│ 3320 ┆ NDARINVB1JW ┆ baselineYea ┆ 01LN  ┆ … ┆ /bin/cp /ho ┆ <HTML><HEAD ┆ 1853    ┆ /usr/local/ │
│      ┆ NR9J        ┆ r1Arm1      ┆       ┆   ┆ me/axon/rkm ┆ >           ┆         ┆ fsl/bin/fsl │
│      ┆             ┆             ┆       ┆   ┆ 160630/s…   ┆ <!--refresh ┆         ┆ _sub -T …   │
│      ┆             ┆             ┆       ┆   ┆             ┆ start-…     ┆         ┆             │
└──────┴─────────────┴─────────────┴───────┴───┴─────────────┴─────────────┴─────────┴─────────────┘

In [4]:
df_error["Lengths"].unique()

shape: (29,)
Series: 'Lengths' [i64]
[
	654
	661
	741
	832
	971
	…
	1954
	1980
	2287
	2357
	3993
]

In [5]:
df_error["Lengths", "Errors"].unique().with_columns(
    pl.col.Errors.str.replace("/home/axon/rkm160630/software/fmri-pipelines/preprocess/workingdir/preproc_FEAT_workflow/_", ""),
    ).with_columns(
    pl.col.Errors.str.replace("_session_baselineYear1Arm1_subject_id","")
    ).with_columns(
    pl.col.Errors.str.replace("_task_sst/_is_nonlinear_False/create_design_fsf_node/sub-","")
    ).with_columns(
    pl.col.Errors.str.replace("_task_sst/_is_nonlinear_False/create_design_fsf_node/sub-","")
    ).glimpse()

Rows: 1588
Columns: 2
$ Lengths <i64> 1898, 654, 654, 1898, 1898, 654, 1856, 654, 654, 1898
$ Errors  <str> '/bin/cp run_1_NDARINVN02TDMZMNDARINVN02TDMZM_ses-baselineYear1Arm1_task-sst_run-01_design.fsf design.fsf\n\n/usr/local/fsl/bin/feat_model design\n\nmkdir .files;cp /usr/local/fsl/doc/fsl.css .files;cp -r /usr/local/fsl/doc/images .files/images\n\n/usr/local/fsl/bin/fsl_sub -T 10 -l logs -N feat0_init   /usr/local/fsl/bin/feat /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-18_11-02-25/sub-NDARINVN02TDMZM_ses-baselineYear1Arm1_task-sst_run-01LN.feat/design.fsf -D /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-18_11-02-25/sub-NDARINVN02TDMZM_ses-baselineYear1Arm1_task-sst_run-01LN.feat -I 1 -init\n3751785\n\n/usr/local/fsl/bin/fsl_sub -T 246 -l logs -N feat2_pre -j 3751785  /usr/local/fsl/bin/feat /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-18_11-02-25/sub-NDARINVN02TDMZM_ses-baselineYear1Arm1_task-sst_run-01LN.feat/design.fsf -D /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-18_11-02-25/sub-NDARINVN02TDMZM_ses-baselineYear1Arm1_task-sst_run-01LN.feat -I 1 -prestats\nError submitting job - child process exited abnormally\n    while executing\n"if { [ catch {\n\nfor { set argindex 1 } { $argindex < $argc } { incr argindex 1 } {\n    switch -- [ lindex $argv $argindex ] {\n\n\t-I {\n\t    incr arginde..."\n    (file "/usr/local/fsl/bin/feat" line 312)\n\n\nFATAL ERROR ENCOUNTERED:\nCOMMAND:\n/usr/local/fsl/bin/fsl_sub -T 246 -l logs -N feat2_pre -j 3751785  /usr/local/fsl/bin/feat /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-18_11-02-25/sub-NDARINVN02TDMZM_ses-baselineYear1Arm1_task-sst_run-01LN.feat/design.fsf -D /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-18_11-02-25/sub-NDARINVN02TDMZM_ses-baselineYear1Arm1_task-sst_run-01LN.feat -I 1 -prestats\nERROR MESSAGE:\nchild process exited abnormally\nEND OF ERROR MESSAGE', '/bin/cp run_1_NDARINVCW82V6Z6NDARINVCW82V6Z6_ses-baselineYear1Arm1_task-sst_run-01_design.fsf design.fsf\n\n/usr/local/fsl/bin/feat_model design\nNo valid\n[onset duration strength]\ntriplets found in /mnt/storage/SST/sub-NDARINVCW82V6Z6/ses-baselineYear1Arm1/func/sub-NDARINVCW82V6Z6_ses-baselineYear1Arm1_task-sst_run-01_incorrGo.tsv\n\nFATAL ERROR ENCOUNTERED:\nCOMMAND:\n/usr/local/fsl/bin/feat_model design\nERROR MESSAGE:\nchild process exited abnormally\nEND OF ERROR MESSAGE', '/bin/cp run_2_NDARINVMXGV952XNDARINVMXGV952X_ses-baselineYear1Arm1_task-sst_run-02_design.fsf design.fsf\n\n/usr/local/fsl/bin/feat_model design\nNo valid\n[onset duration strength]\ntriplets found in /mnt/storage/SST/sub-NDARINVMXGV952X/ses-baselineYear1Arm1/func/sub-NDARINVMXGV952X_ses-baselineYear1Arm1_task-sst_run-02_incorrGo.tsv\n\nFATAL ERROR ENCOUNTERED:\nCOMMAND:\n/usr/local/fsl/bin/feat_model design\nERROR MESSAGE:\nchild process exited abnormally\nEND OF ERROR MESSAGE', '/bin/cp run_2_NDARINVN0XCHU07NDARINVN0XCHU07_ses-baselineYear1Arm1_task-sst_run-02_design.fsf design.fsf\n\n/usr/local/fsl/bin/feat_model design\n\nmkdir .files;cp /usr/local/fsl/doc/fsl.css .files;cp -r /usr/local/fsl/doc/images .files/images\n\n/usr/local/fsl/bin/fsl_sub -T 10 -l logs -N feat0_init   /usr/local/fsl/bin/feat /mnt/WarrenNAS/Data/processed_mri/SST/2026-02-09_16-21-39/sub-NDARINVN0XCHU07_ses-baselineYear1Arm1_task-sst_run-02LN.feat/design.fsf -D /mnt/WarrenNAS/Data/processed_mri/SST/2026-02-09_16-21-39/sub-NDARINVN0XCHU07_ses-baselineYear1Arm1_task-sst_run-02LN.feat -I 1 -init\n1187171\n\n/usr/local/fsl/bin/fsl_sub -T 246 -l logs -N feat2_pre -j 1187171  /usr/local/fsl/bin/feat /mnt/WarrenNAS/Data/processed_mri/SST/2026-02-09_16-21-39/sub-NDARINVN0XCHU07_ses-baselineYear1Arm1_task-sst_run-02LN.feat/design.fsf -D /mnt/WarrenNAS/Data/processed_mri/SST/2026-02-09_16-21-39/sub-NDARINVN0XCHU07_ses-baselineYear1Arm1_task-sst_run-02LN.feat -I 1 -prestats\nError submitting job - child process exited abnormally\n    while executing\n"if { [ catch {\n\nfor { set argindex 1 } { $argindex < $argc } { incr argindex 1 } {\n    switch -- [ lindex $argv $argindex ] {\n\n\t-I {\n\t    incr arginde..."\n    (file "/usr/local/fsl/bin/feat" line 312)\n\n\nFATAL ERROR ENCOUNTERED:\nCOMMAND:\n/usr/local/fsl/bin/fsl_sub -T 246 -l logs -N feat2_pre -j 1187171  /usr/local/fsl/bin/feat /mnt/WarrenNAS/Data/processed_mri/SST/2026-02-09_16-21-39/sub-NDARINVN0XCHU07_ses-baselineYear1Arm1_task-sst_run-02LN.feat/design.fsf -D /mnt/WarrenNAS/Data/processed_mri/SST/2026-02-09_16-21-39/sub-NDARINVN0XCHU07_ses-baselineYear1Arm1_task-sst_run-02LN.feat -I 1 -prestats\nERROR MESSAGE:\nchild process exited abnormally\nEND OF ERROR MESSAGE', '/bin/cp run_1_NDARINV0BVP2PTDNDARINV0BVP2PTD_ses-baselineYear1Arm1_task-sst_run-01_design.fsf design.fsf\n\n/usr/local/fsl/bin/feat_model design\n\nmkdir .files;cp /usr/local/fsl/doc/fsl.css .files;cp -r /usr/local/fsl/doc/images .files/images\n\n/usr/local/fsl/bin/fsl_sub -T 10 -l logs -N feat0_init   /usr/local/fsl/bin/feat /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-17_07-55-33/sub-NDARINV0BVP2PTD_ses-baselineYear1Arm1_task-sst_run-01LN.feat/design.fsf -D /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-17_07-55-33/sub-NDARINV0BVP2PTD_ses-baselineYear1Arm1_task-sst_run-01LN.feat -I 1 -init\n1295172\n\n/usr/local/fsl/bin/fsl_sub -T 246 -l logs -N feat2_pre -j 1295172  /usr/local/fsl/bin/feat /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-17_07-55-33/sub-NDARINV0BVP2PTD_ses-baselineYear1Arm1_task-sst_run-01LN.feat/design.fsf -D /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-17_07-55-33/sub-NDARINV0BVP2PTD_ses-baselineYear1Arm1_task-sst_run-01LN.feat -I 1 -prestats\nError submitting job - child process exited abnormally\n    while executing\n"if { [ catch {\n\nfor { set argindex 1 } { $argindex < $argc } { incr argindex 1 } {\n    switch -- [ lindex $argv $argindex ] {\n\n\t-I {\n\t    incr arginde..."\n    (file "/usr/local/fsl/bin/feat" line 312)\n\n\nFATAL ERROR ENCOUNTERED:\nCOMMAND:\n/usr/local/fsl/bin/fsl_sub -T 246 -l logs -N feat2_pre -j 1295172  /usr/local/fsl/bin/feat /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-17_07-55-33/sub-NDARINV0BVP2PTD_ses-baselineYear1Arm1_task-sst_run-01LN.feat/design.fsf -D /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-17_07-55-33/sub-NDARINV0BVP2PTD_ses-baselineYear1Arm1_task-sst_run-01LN.feat -I 1 -prestats\nERROR MESSAGE:\nchild process exited abnormally\nEND OF ERROR MESSAGE', '/bin/cp run_1_NDARINVDTHJM3Y9NDARINVDTHJM3Y9_ses-baselineYear1Arm1_task-sst_run-01_design.fsf design.fsf\n\n/usr/local/fsl/bin/feat_model design\nNo valid\n[onset duration strength]\ntriplets found in /mnt/storage/SST/sub-NDARINVDTHJM3Y9/ses-baselineYear1Arm1/func/sub-NDARINVDTHJM3Y9_ses-baselineYear1Arm1_task-sst_run-01_incorrGo.tsv\n\nFATAL ERROR ENCOUNTERED:\nCOMMAND:\n/usr/local/fsl/bin/feat_model design\nERROR MESSAGE:\nchild process exited abnormally\nEND OF ERROR MESSAGE', '/bin/cp run_1_NDARINVF0G439YWNDARINVF0G439YW_ses-baselineYear1Arm1_task-sst_run-01_design.fsf design.fsf\n\n/usr/local/fsl/bin/feat_model design\n\nmkdir .files;cp /usr/local/fsl/doc/fsl.css .files;cp -r /usr/local/fsl/doc/images .files/images\n\n/usr/local/fsl/bin/fsl_sub -T 10 -l logs -N feat0_init   /usr/local/fsl/bin/feat /mnt/WarrenNAS/Projects/processed_mri/sst/baseline/sub-NDARINVF0G439YW_ses-baselineYear1Arm1_task-sst_run-01LN.feat/design.fsf -D /mnt/WarrenNAS/Projects/processed_mri/sst/baseline/sub-NDARINVF0G439YW_ses-baselineYear1Arm1_task-sst_run-01LN.feat -I 1 -init\n2143822\n\n/usr/local/fsl/bin/fsl_sub -T 246 -l logs -N feat2_pre -j 2143822  /usr/local/fsl/bin/feat /mnt/WarrenNAS/Projects/processed_mri/sst/baseline/sub-NDARINVF0G439YW_ses-baselineYear1Arm1_task-sst_run-01LN.feat/design.fsf -D /mnt/WarrenNAS/Projects/processed_mri/sst/baseline/sub-NDARINVF0G439YW_ses-baselineYear1Arm1_task-sst_run-01LN.feat -I 1 -prestats\nError submitting job - child process exited abnormally\n    while executing\n"if { [ catch {\n\nfor { set argindex 1 } { $argindex < $argc } { incr argindex 1 } {\n    switch -- [ lindex $argv $argindex ] {\n\n\t-I {\n\t    incr arginde..."\n    (file "/usr/local/fsl/bin/feat" line 312)\n\n\nFATAL ERROR ENCOUNTERED:\nCOMMAND:\n/usr/local/fsl/bin/fsl_sub -T 246 -l logs -N feat2_pre -j 2143822  /usr/local/fsl/bin/feat /mnt/WarrenNAS/Projects/processed_mri/sst/baseline/sub-NDARINVF0G439YW_ses-baselineYear1Arm1_task-sst_run-01LN.feat/design.fsf -D /mnt/WarrenNAS/Projects/processed_mri/sst/baseline/sub-NDARINVF0G439YW_ses-baselineYear1Arm1_task-sst_run-01LN.feat -I 1 -prestats\nERROR MESSAGE:\nchild process exited abnormally\nEND OF ERROR MESSAGE', '/bin/cp run_1_NDARINVWP2U8M5YNDARINVWP2U8M5Y_ses-baselineYear1Arm1_task-sst_run-01_design.fsf design.fsf\n\n/usr/local/fsl/bin/feat_model design\nNo valid\n[onset duration strength]\ntriplets found in /mnt/storage/SST/sub-NDARINVWP2U8M5Y/ses-baselineYear1Arm1/func/sub-NDARINVWP2U8M5Y_ses-baselineYear1Arm1_task-sst_run-01_incorrGo.tsv\n\nFATAL ERROR ENCOUNTERED:\nCOMMAND:\n/usr/local/fsl/bin/feat_model design\nERROR MESSAGE:\nchild process exited abnormally\nEND OF ERROR MESSAGE', '/bin/cp run_1_NDARINV00HEV6HBNDARINV00HEV6HB_ses-baselineYear1Arm1_task-sst_run-01_design.fsf design.fsf\n\n/usr/local/fsl/bin/feat_model design\nNo valid\n[onset duration strength]\ntriplets found in /mnt/storage/SST/sub-NDARINV00HEV6HB/ses-baselineYear1Arm1/func/sub-NDARINV00HEV6HB_ses-baselineYear1Arm1_task-sst_run-01_incorrGo.tsv\n\nFATAL ERROR ENCOUNTERED:\nCOMMAND:\n/usr/local/fsl/bin/feat_model design\nERROR MESSAGE:\nchild process exited abnormally\nEND OF ERROR MESSAGE', '/bin/cp run_1_NDARINV2KBLDWXWNDARINV2KBLDWXW_ses-baselineYear1Arm1_task-sst_run-01_design.fsf design.fsf\n\n/usr/local/fsl/bin/feat_model design\n\nmkdir .files;cp /usr/local/fsl/doc/fsl.css .files;cp -r /usr/local/fsl/doc/images .files/images\n\n/usr/local/fsl/bin/fsl_sub -T 10 -l logs -N feat0_init   /usr/local/fsl/bin/feat /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-17_07-55-33/sub-NDARINV2KBLDWXW_ses-baselineYear1Arm1_task-sst_run-01LN.feat/design.fsf -D /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-17_07-55-33/sub-NDARINV2KBLDWXW_ses-baselineYear1Arm1_task-sst_run-01LN.feat -I 1 -init\n2216456\n\n/usr/local/fsl/bin/fsl_sub -T 246 -l logs -N feat2_pre -j 2216456  /usr/local/fsl/bin/feat /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-17_07-55-33/sub-NDARINV2KBLDWXW_ses-baselineYear1Arm1_task-sst_run-01LN.feat/design.fsf -D /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-17_07-55-33/sub-NDARINV2KBLDWXW_ses-baselineYear1Arm1_task-sst_run-01LN.feat -I 1 -prestats\nError submitting job - child process exited abnormally\n    while executing\n"if { [ catch {\n\nfor { set argindex 1 } { $argindex < $argc } { incr argindex 1 } {\n    switch -- [ lindex $argv $argindex ] {\n\n\t-I {\n\t    incr arginde..."\n    (file "/usr/local/fsl/bin/feat" line 312)\n\n\nFATAL ERROR ENCOUNTERED:\nCOMMAND:\n/usr/local/fsl/bin/fsl_sub -T 246 -l logs -N feat2_pre -j 2216456  /usr/local/fsl/bin/feat /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-17_07-55-33/sub-NDARINV2KBLDWXW_ses-baselineYear1Arm1_task-sst_run-01LN.feat/design.fsf -D /mnt/WarrenNAS/Data/processed_mri/SST/2025-12-17_07-55-33/sub-NDARINV2KBLDWXW_ses-baselineYear1Arm1_task-sst_run-01LN.feat -I 1 -prestats\nERROR MESSAGE:\nchild process exited abnormally\nEND OF ERROR MESSAGE'

In [10]:
damika_csv = "/mnt/storage/failed_roi/fsl_true_fatal_errors_latest.csv"
df_error_2 = pl.read_csv(damika_csv)
df_error_2

shape: (60, 9)
┌─────────────┬─────────────┬──────┬─────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ subject_id  ┆ session     ┆ task ┆ run ┆ … ┆ error_messa ┆ missing_ev_ ┆ design_com ┆ html_file  │
│ ---         ┆ ---         ┆ ---  ┆ --- ┆   ┆ ge          ┆ file        ┆ mand       ┆ ---        │
│ str         ┆ str         ┆ str  ┆ i64 ┆   ┆ ---         ┆ ---         ┆ ---        ┆ str        │
│             ┆             ┆      ┆     ┆   ┆ str         ┆ str         ┆ str        ┆            │
╞═════════════╪═════════════╪══════╪═════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ NDARINV0X4A ┆ baselineYea ┆ sst  ┆ 1   ┆ … ┆ ERROR       ┆ N/A         ┆ /bin/cp    ┆ /mnt/Warre │
│ 2LKW        ┆ r1Arm1      ┆      ┆     ┆   ┆ MESSAGE:    ┆             ┆ /home/axon ┆ nNAS_basel │
│             ┆             ┆      ┆     ┆   ┆ child       ┆             ┆ /rkm160630 ┆ ine/sub-ND │
│             ┆             ┆      ┆     ┆   ┆ killed: h…  ┆             ┆ /s…        ┆ …          │
│ NDARINVD9ZE ┆ baselineYea ┆ sst  ┆ 2   ┆ … ┆ ERROR       ┆ N/A         ┆ /bin/cp    ┆ /mnt/Warre │
│ J36L        ┆ r1Arm1      ┆      ┆     ┆   ┆ MESSAGE:    ┆             ┆ /home/axon ┆ nNAS_basel │
│             ┆             ┆      ┆     ┆   ┆ child       ┆             ┆ /rkm160630 ┆ ine/sub-ND │
│             ┆             ┆      ┆     ┆   ┆ killed: h…  ┆             ┆ /s…        ┆ …          │
│ NDARINVDAMX ┆ baselineYea ┆ sst  ┆ 1   ┆ … ┆ ERROR       ┆ N/A         ┆ /bin/cp    ┆ /mnt/Warre │
│ KG0G        ┆ r1Arm1      ┆      ┆     ┆   ┆ MESSAGE:    ┆             ┆ /home/axon ┆ nNAS_basel │
│             ┆             ┆      ┆     ┆   ┆ child       ┆             ┆ /rkm160630 ┆ ine/sub-ND │
│             ┆             ┆      ┆     ┆   ┆ killed: h…  ┆             ┆ /s…        ┆ …          │
│ NDARINVDGVA ┆ baselineYea ┆ sst  ┆ 2   ┆ … ┆ ERROR       ┆ N/A         ┆ /bin/cp    ┆ /mnt/Warre │
│ DKJA        ┆ r1Arm1      ┆      ┆     ┆   ┆ MESSAGE:    ┆             ┆ /home/axon ┆ nNAS_basel │
│             ┆             ┆      ┆     ┆   ┆ child       ┆             ┆ /rkm160630 ┆ ine/sub-ND │
│             ┆             ┆      ┆     ┆   ┆ killed: h…  ┆             ┆ /s…        ┆ …          │
│ NDARINV13GH ┆ baselineYea ┆ sst  ┆ 1   ┆ … ┆ ERROR       ┆ N/A         ┆ /bin/cp    ┆ /mnt/Warre │
│ 02YK        ┆ r1Arm1      ┆      ┆     ┆   ┆ MESSAGE:    ┆             ┆ /home/axon ┆ nNAS_basel │
│             ┆             ┆      ┆     ┆   ┆ child       ┆             ┆ /rkm160630 ┆ ine/sub-ND │
│             ┆             ┆      ┆     ┆   ┆ killed: h…  ┆             ┆ /s…        ┆ …          │
│ …           ┆ …           ┆ …    ┆ …   ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ NDARINV138R ┆ baselineYea ┆ sst  ┆ 2   ┆ … ┆ ERROR       ┆ N/A         ┆ /bin/cp    ┆ /mnt/Warre │
│ G20T        ┆ r1Arm1      ┆      ┆     ┆   ┆ MESSAGE:    ┆             ┆ /home/axon ┆ nNAS_basel │
│             ┆             ┆      ┆     ┆   ┆ child       ┆             ┆ /rkm160630 ┆ ine/sub-ND │
│             ┆             ┆      ┆     ┆   ┆ killed: h…  ┆             ┆ /s…        ┆ …          │
│ NDARINV15VX ┆ baselineYea ┆ sst  ┆ 2   ┆ … ┆ ERROR       ┆ N/A         ┆ /bin/cp    ┆ /mnt/Warre │
│ 8FJL        ┆ r1Arm1      ┆      ┆     ┆   ┆ MESSAGE:    ┆             ┆ /home/axon ┆ nNAS_basel │
│             ┆             ┆      ┆     ┆   ┆ child       ┆             ┆ /rkm160630 ┆ ine/sub-ND │
│             ┆             ┆      ┆     ┆   ┆ killed: h…  ┆             ┆ /s…        ┆ …          │
│ NDARINVDC5L ┆ baselineYea ┆ sst  ┆ 2   ┆ … ┆ ERROR       ┆ N/A         ┆ /bin/cp    ┆ /mnt/Warre │
│ MY0K        ┆ r1Arm1      ┆      ┆     ┆   ┆ MESSAGE:    ┆             ┆ /home/axon ┆ nNAS_basel │
│             ┆             ┆      ┆     ┆   ┆ child       ┆             ┆ /rkm160630 ┆ ine/sub-ND │
│             ┆             ┆      ┆     ┆   ┆ killed: h…  ┆             ┆ /s…        ┆ …          │
│ NDARINVDHDL ┆ baselineYea ┆ sst  ┆ 1   ┆ … ┆ ERROR       ┆ N/A         ┆ /bin/cp    ┆ /mnt/Warre │
│ J5CV        ┆ r1Arm1      ┆      ┆     ┆   ┆ MESSAGE:    ┆             ┆ /home/axon ┆ nNAS_basel │
│             ┆             ┆      ┆     ┆   ┆ child       ┆             ┆ /rkm160630 ┆ ine/sub-ND │
│             ┆             ┆      ┆     ┆   ┆ killed: h…  ┆             ┆ /s…        ┆ …          │
│ NDARINV1164 ┆ baselineYea ┆ sst  ┆ 2   ┆ … ┆ ERROR       ┆ N/A         ┆ /bin/cp    ┆ /mnt/Warre │
│ KR5T        ┆ r1Arm1      ┆      ┆     ┆   ┆ MESSAGE:    ┆             ┆ /home/axon ┆ nNAS_basel │
│             ┆             ┆      ┆     ┆   ┆ child       ┆             ┆ /rkm160630 ┆ ine/sub-ND │
│             ┆             ┆      ┆     ┆   ┆ killed: h…  ┆             ┆ /s…        ┆ …          │
└─────────────┴─────────────┴──────┴─────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [11]:
df_error_2["error_message"].unique().to_list()

['ERROR MESSAGE: child killed: hangup',
 'ERROR MESSAGE: child process exited abnormally']

In [20]:
df_error_2.group_by("error_message").agg(pl.col.html_file.sample(1))

shape: (2, 2)
┌─────────────────────────────────┬─────────────────────────────────┐
│ error_message                   ┆ html_file                       │
│ ---                             ┆ ---                             │
│ str                             ┆ list[str]                       │
╞═════════════════════════════════╪═════════════════════════════════╡
│ ERROR MESSAGE: child killed: h… ┆ ["/mnt/WarrenNAS_baseline/sub-… │
│ ERROR MESSAGE: child process e… ┆ ["/mnt/WarrenNAS_baseline/2025… │
└─────────────────────────────────┴─────────────────────────────────┘

In [9]:
! less /mnt/WarrenNAS_baseline/sub-NDARINV8E73MX03_ses-baselineYear1Arm1_task-sst_run-02LN+.feat/report_log.html

/mnt/WarrenNAS_baseline/sub-NDARINV8E73MX03_ses-baselineYear1Arm1_task-sst_run-02LN+.feat/report_log.html: Permission denied